#!/bin/env python3

import json
from os.path import isfile, expanduser

HOSTS='/etc/hosts'
BLACKLIST=expanduser('~/.lulz_mode.blacklist.json')

HEADER='# >>> blacklist'
FOOTER='# <<< blacklist'

class HostsFormatError(Exception):
    def __init__(self, message):
        self.message = \
        'Unexpected /etc/hosts format. You need to manually edit /etc/hosts'

class NoBlacklistError(Exception):
    def __init__(self, message):
        self.message = \
        f'Sorry. Missing {BLACKLIST}. You need to manually edit your /etc/hosts.'

def is_lulz_mode():
    with open(HOSTS) as f: lines = f.readlines()
    matches = len(tuple(filter(lambda l: HEADER in l, lines)))
    if matches > 1: raise HostsFormatError()
    return matches == 0

def toggle_lulz_mode():
    if not isfile(BLACKLIST): raise NoBlacklistError()

    with open(BLACKLIST) as f: blacklist = json.loads(f.read())

    if is_lulz_mode():
        payload = [HEADER]
        for host in blacklist: payload.append(f'0.0.0.0 {host}')
        payload.append(FOOTER)

        with open(HOSTS) as f: lines = f.readlines()
        payload.extend(lines)
        with open(HOSTS, 'w') as f: f.write('\n'.join(payload))

    else:
        with open(HOSTS) as f:
            lines = list(map(lambda l: l.strip(), f.readlines()))

        for host in blacklist:
            formatted = f'0.0.0.0 {host}'
            if formatted in lines: lines.remove(formatted)

        lines.remove(HEADER)
        lines.remove(FOOTER)

        with open(HOSTS, 'w') as f: f.write('\n'.join(lines))


if __name__ == '__main__':
    from argparse import ArgumentParser
    parser = ArgumentParser(
        description='When your finals are close, blacklist distracting hosts.'
    )
    parser.add_argument(
        '--toggle', help='Toggle lulz mode', action='store_true'
    )

    args = parser.parse_args()

    if args.toggle: toggle_lulz_mode()
    print('Lulzmode: {}'.format('✔' if is_lulz_mode() else '✖')) 
